"""add reports table

Revision ID: b1ae98de1da7
Revises: 6480fb3895ed
Create Date: 2026-05-08 00:05:59.535064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1ae98de1da7'
down_revision: Union[str, Sequence[str], None] = '6480fb3895ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('energy_yield', sa.Float(), nullable=False),
    sa.Column('monthly_yield', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('radiation', sa.Float(), nullable=False),
    sa.Column('specific_yield', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_scenario_id'), 'reports', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_scenario_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
