"""split location into more fields

Revision ID: d61f4516925c
Revises: 
Create Date: 2026-05-04 13:03:36.196322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61f4516925c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('projects', sa.Column('long', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'long')
    op.drop_column('projects', 'lat')
    # ### end Alembic commands ###
