"""general fixes

Revision ID: 6480fb3895ed
Revises: 7f192e5897d3
Create Date: 2026-05-04 20:40:50.183378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6480fb3895ed'
down_revision: Union[str, Sequence[str], None] = '7f192e5897d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technology', sa.Enum('mono_c_Si', 'multi_c_Si', 'thin_film', name='pvtech'), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('nominal_power', sa.Float(), nullable=False),
    sa.Column('temp_coeff_pmax', sa.Float(), nullable=False),
    sa.Column('noct', sa.Float(), nullable=False),
    sa.Column('ptc', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('projects', 'long')
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_scenarios_module_id'), 'scenarios', ['module_id'], unique=False)
    op.create_foreign_key(None, 'scenarios', 'modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_index(op.f('ix_scenarios_module_id'), table_name='scenarios')
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('projects', sa.Column('long', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('projects', 'lon')
    op.drop_table('modules')
    # ### end Alembic commands ###
