"""add chart_data to reports table

Revision ID: 433d7d4fdf8f
Revises: 6852cc286077
Create Date: 2026-07-09 15:52:52.875071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433d7d4fdf8f'
down_revision: Union[str, Sequence[str], None] = '6852cc286077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('chart_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'chart_data')
    # ### end Alembic commands ###
