"""projects model: add is_demo column and make user nullable

Revision ID: f1e1ef289dc8
Revises: dcb05fc5fb92
Create Date: 2026-08-02 18:43:29.844598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e1ef289dc8'
down_revision: Union[str, Sequence[str], None] = 'dcb05fc5fb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('projects', 'is_demo')
    # ### end Alembic commands ###
