"""add monthy irradiance and perf ratio fields to reports table

Revision ID: 6852cc286077
Revises: 39f8ee18e86b
Create Date: 2026-07-09 12:21:19.241151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6852cc286077'
down_revision: Union[str, Sequence[str], None] = '39f8ee18e86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('monthly_radiation', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('perf_ratio', sa.Float(), nullable=True))
    op.execute("ALTER TABLE reports ALTER COLUMN monthly_yield TYPE JSON USING monthly_yield::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE reports ALTER COLUMN monthly_yield TYPE VARCHAR USING monthly_yield::text")
    op.drop_column('reports', 'perf_ratio')
    op.drop_column('reports', 'monthly_radiation')

    # ### end Alembic commands ###
