"""refactor: data validation and error handling improvements

Revision ID: ccd6d2aa3dd5
Revises: de3704db31da
Create Date: 2026-06-04 16:50:50.434977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccd6d2aa3dd5'
down_revision: Union[str, Sequence[str], None] = 'de3704db31da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reports_scenario_id_unique', 'reports', ['scenario_id'], unique=True)
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_reports_scenario_id_unique', table_name='reports')
    # ### end Alembic commands ###
