"""add CdTe and CIGS to PVTech enum

Revision ID: 39f8ee18e86b
Revises: 33684ae95896
Create Date: 2026-07-03 12:41:33.332285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f8ee18e86b'
down_revision: Union[str, Sequence[str], None] = '33684ae95896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE pvtech ADD VALUE IF NOT EXISTS 'cdte'")
    op.execute("ALTER TYPE pvtech ADD VALUE IF NOT EXISTS 'cigs'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
