"""add country_code to project model

Revision ID: dcb05fc5fb92
Revises: 433d7d4fdf8f
Create Date: 2026-07-20 15:23:19.134090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcb05fc5fb92'
down_revision: Union[str, Sequence[str], None] = '433d7d4fdf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'country_code')
    # ### end Alembic commands ###
